
[project]
name = "testing-example"
authors = ["LNow", "Nikos Baxevanis"]
telemetry = false

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

[contracts.example]
path = "contracts/example.clar"
